import type { MetadataRoute } from 'next';
import blogPostArchive from '../blogPostArchive.json';
// films.json is generated by the scraper, so its inferred shape depends on
// whatever data happens to be present (and it is absent on a fresh clone).
// Typing it as FilmsIndex keeps the sitemap checkable without the real file.
import filmsJson from '../data/films.json';
import type { FilmsIndex } from '../types';
import { CATEGORIES } from '../data/blogCategories';

const filmsData = filmsJson as FilmsIndex;

export const dynamic = 'force-static';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://a-450.com';

  const blogPages = blogPostArchive.flatMap((blog) => {
    const [day, month, year] = blog.dateAdded.split('/').map(Number);
    const date = new Date(Date.UTC(year, month - 1, day));

    return {
      url: `${baseUrl}${blog.link}`,
      lastModified: date.toISOString(),
    };
  });

  const blogCategoryPages = CATEGORIES.map(({ slug }) => ({
    url: `${baseUrl}/blog/${slug}`,
    lastModified: new Date().toISOString(),
  }));

  // dateAdded is optional on FilmDetail, so fall back to now rather than
  // emitting an "Invalid Date" lastModified into the sitemap.
  const filmPages = Object.values(filmsData).map((film) => ({
    url: `${baseUrl}/films/${film.slug}`,
    lastModified: (film.dateAdded
      ? new Date(film.dateAdded)
      : new Date()
    ).toISOString(),
  }));

  return [
    { url: baseUrl, lastModified: new Date().toISOString() },
    { url: `${baseUrl}/blog`, lastModified: new Date().toISOString() },
    { url: `${baseUrl}/film-listings`, lastModified: new Date().toISOString() },
    ...blogCategoryPages,
    ...blogPages,
    ...filmPages,
  ];
}
